id: b5b4ef0abb3348f28a142c09fc429c3e
initial_creation_type: ocr
source_metadata:
  volumes:
    f2f52c04dc414bd89e5d852045a3c00f:
      base_file: v001.txt
      image_group_id: I1PD95846
      title: བསྟོད་པ་ལས་འདས་པར་བསྟོད་པ།
      total_pages: 1539
      volume_number: 1
